### ISSUE TITLE
MVP - Distance Based Detection

### ISSUE THREAD

**Issue by laurenkl96** [TheGameDevelopmentClub/Ludum-Dare-37#3]
Create a Prefab in Unity that will catch the player if they get too close

**Comment by NickABoen** [comment]
Circular Detector is done, working on Cone Detector. Will merge to master when finished

**Comment by NickABoen** [comment]
Circluar detection and conical detection is now finished and can be added to game objects as scripts. There is an invoker component that can be used to create call methods on a few key events.
